on: 
  release: 
    types: [published]
jobs:
  generate-and-publish-common:
    runs-on: ubuntu-latest
    name: Common vocab artifact generation and publication 
    steps:
     # Makes the current repository available to the workflow.
    - name: Checkout repo
      uses: actions/checkout@v2
      # Initializes node for the runner.
    - name: Node setup
      uses: actions/setup-node@v1
      with:
        node-version: '12.12.0'
        registry-url: https://npm.pkg.github.com/
        scope: '@inrupt'
      # The following sets up Java and Maven, which is required for Java artifacts generation
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Generate Maven settings for Nexus publication
      uses: ./.github/fill-template
      with: 
        template-path: ./.github/maven-settings.hbs
        output-path: ./settings.xml
      env: 
        SERVER_ID_RELEASE: nexus-releases
        SERVER_URL_RELEASE: https://nexus.inrupt.com/repository/maven-releases/
        SERVER_ID_SNAPSHOT: nexus-snapshots
        SERVER_URL_SNAPSHOT: https://nexus.inrupt.com/repository/maven-snapshots/
        SERVER_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        SERVER_PASSWORD: ${{ secrets.NEXUS_TOKEN }}
      # The following action is defined in the current repo.
      # It reads the expected generator version from the YAML file.
    - name: Get generator version (Common)
      uses: ./.github/lit-generator-version/
      id: generator-version-common
      with: 
        vocab-config-path: Common/Vocab-List-Solid-Common.yml
      # Installs the artifact generator from its github package.
      # The package is renamed in order to enable having different versions side-by-side.
    - name: Generator installation
      run: npm install artifact-generator${{steps.generator-version-common.outputs.vocab-generator-version}}@npm:@inrupt/lit-artifact-generator@${{steps.generator-version-common.outputs.vocab-generator-version}} --registry https://npm.pkg.github.com/inrupt
      env:
        NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - name: Webpack installation
      run: npm install webpack webpack-cli -g
      # Use the generator to generate and publish the package.
    - name: Generation and publication
      # Note that only the NPM artifacts are released on the 'release' event,
      # because the Maven artifacts are released on push (because they support
      # -SNAPSHOT versions).
      run: node node_modules/artifact-generator${{steps.generator-version-common.outputs.vocab-generator-version}}/index.js generate -l Common/Vocab-List-Solid-Common.yml -p githubNpm --noprompt
      env:
        NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}