version: 2
updates:
  # Enable daily version updates for prod dependencies
  - package-ecosystem: "npm"
    directory: "/.github/fill-template"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/.github/artifact-generator-version"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check the npm registry for updates once a week
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
