on:
  pull_request:
    branches:
      - master

jobs:
    validate_pr_common:
      runs-on: ubuntu-latest
      name: Inrupt Common vocabulary validation
      steps:
      # Setup
      - name: Checkout repo
        uses: actions/checkout@v2
      # Initializes node for the runner
      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: '12.12.0'
          registry-url: https://npm.pkg.github.com/
          scope: '@inrupt'
      # The following step sets up Maven.
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          # These values are used in the `settings.xml` Maven config file
          server-id: nexus-snapshots # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: ${{ secrets.NEXUS_USERNAME }}
          server-password: ${{ secrets.NEXUS_TOKEN }}
      # The following action is defined in the current repo
      # It reads the expected generator version from the YAML file
      - name: Get generator version (Common)
        uses: ./.github/lit-generator-version/
        id: generator-version-common
        with:
          vocab-config-path: Common/Vocab-List-Inrupt-Common.yml
      - name: Generate proper Maven settings
        uses: ./.github/fill-template
        with:
          template-path: ./.github/maven-settings.hbs
          output-path: ./settings.xml
        env:
          SERVER_ID_RELEASE: nexus-releases
          SERVER_URL_RELEASE: https://nexus.inrupt.com/repository/maven-releases/
          SERVER_ID_SNAPSHOT: nexus-snapshots
          SERVER_URL_SNAPSHOT: https://nexus.inrupt.com/repository/maven-snapshots/
          SERVER_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.NEXUS_TOKEN }}
      # Installs the artifact generator from its github package
      # The package is renamed in order to enable having different versions side-by-side
      - name: Install LIT Artifact Generator
        run: npm install artifact-generator${{steps.generator-version-common.outputs.vocab-generator-version}}@npm:@inrupt/lit-artifact-generator@${{steps.generator-version-common.outputs.vocab-generator-version}} --registry https://npm.pkg.github.com/inrupt
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - run: node node_modules/artifact-generator${{steps.generator-version-common.outputs.vocab-generator-version}}/index.js generate -l Common/Vocab-List-Inrupt-Common.yml --noprompt
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    validate_pr_service:
      runs-on: ubuntu-latest
      name: Inrupt Service vocabulary validation
      steps:
      # Setup
      - name: Checkout repo
        uses: actions/checkout@v2
      # Initializes node for the runner
      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: '12.12.0'
          registry-url: https://npm.pkg.github.com/
          scope: '@inrupt'
      # The following step sets up Maven.
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          # These values are used in the `settings.xml` Maven config file
          server-id: nexus-snapshots # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: ${{ secrets.NEXUS_USERNAME }}
          server-password: ${{ secrets.NEXUS_TOKEN }}
      # The following action is defined in the current repo
      # It reads the expected generator version from the YAML file
      - name: Get generator version
        uses: ./.github/lit-generator-version/
        id: generator-version-service
        with:
          vocab-config-path: Service/Vocab-List-Inrupt-Service.yml
      - name: Generate proper Maven settings
        uses: ./.github/fill-template
        with:
          template-path: ./.github/maven-settings.hbs
          output-path: ./settings.xml
        env:
          SERVER_ID_RELEASE: nexus-releases
          SERVER_URL_RELEASE: https://nexus.inrupt.com/repository/maven-releases/
          SERVER_ID_SNAPSHOT: nexus-snapshots
          SERVER_URL_SNAPSHOT: https://nexus.inrupt.com/repository/maven-snapshots/
          SERVER_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.NEXUS_TOKEN }}
      # Installs the artifact generator from its github package
      # The package is renamed in order to enable having different versions side-by-side
      - name: Install LIT Artifact Generator
        run: npm install artifact-generator${{steps.generator-version-service.outputs.vocab-generator-version}}@npm:@inrupt/lit-artifact-generator@${{steps.generator-version-service.outputs.vocab-generator-version}} --registry https://npm.pkg.github.com/inrupt
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - run: node node_modules/artifact-generator${{steps.generator-version-service.outputs.vocab-generator-version}}/index.js generate -l Service/Vocab-List-Inrupt-Service.yml --noprompt
      env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
