#
# This file contains a simple list of vocabularies that we bundle together to
# form the collective set of Inrupt Common vocabularies.
#
# For example, for Java developers we can generate a single JAR, or for
# JavaScript we can generate a single npm module, that developers can depend
# on directly and easily get immediate access to source-code constants for all
# the terms in all of these vocabularies.
#
# Local vocabularies can be provided relative to the location of this resource
# list file.
#
artifactName: vocab-inrupt-client-application
artifactGeneratorVersion: 1.0.0

versioning:
  type: git
  url: https://github.com/inrupt/solid-common-vocab-rdf.git
  versioningTemplates:
    - templateInternal: ".gitignore.hbs"
      fileName: ".gitignore"

license:
  path: "../../LICENSE"
  fileName: "LICENSE"
  header: "../../LICENSE_HEADER.js"
  name: "MIT"

artifactToGenerate:
  - programmingLanguage: Java
    artifactVersion: 0.8.2-SNAPSHOT

    artifactDirectoryName: Java
    sourceFileExtension: java
    javaPackageName: com.inrupt.vocab.inrupt.client.application

    solidCommonVocabVersion: 0.0.3
    rdf4jVersion: 3.4.2
    templateInternal: solidCommonVocabDependent/java/rdf4j/vocab.hbs

    # Currently we're just adding terms as they occur in vocabs, and not all possible keywords.
    languageKeywordsToUnderscore:
      - class     # Defined in VCard.
      - abstract  # Defined in DCTerms.
      - default   # Defined in ACL
    packaging:
    - packagingTool: maven
      groupId: com.inrupt
      publish:
      - key: "mavenLocal"
        command: "mvn --version && mvn install"
      - key: "mavenRemote"
        command: "mvn deploy"
      - key: "cloudsmith"
        command: "mvn -s /home/runner/work/solid-common-vocab-rdf/solid-common-vocab-rdf/settings.xml deploy --log-file ../../../mvn-deploy.log"
      packagingTemplates: 
      - templateInternal: solidCommonVocabDependent/java/rdf4j/pom.hbs
        fileName: pom.xml
      repository:
      - type: repository
        id: cloudsmith-staging
        url: https://maven.cloudsmith.io/inrupt/sdk-staging/
      - type: snapshotRepository
        id: cloudsmith-development
        url: https://maven.cloudsmith.io/inrupt/sdk-development/

  # This is the configuration of the DEFAULT VocabTerm TypeScript artifact -
  # i.e., where the name of the generated npm module does not contain details
  # of the underlying RDF library dependencies (e.g., whether it depends on
  # RDF/JS or a specific implementation, etc.).
  - programmingLanguage: TypeScript
    artifactVersion: "1.0.0"

    artifactDirectoryName: TypeScript-VocabTerm
    sourceFileExtension: ts
    artifactSuffix: -vocabterm

    solidCommonVocabVersion: "^1.0.0"
    rdfjsImplVersion: "^1.0.4"
    templateInternal: solidCommonVocabDependent/typescript/rdfjsRdfDataFactory/vocab.hbs

    packaging:
      - packagingTool: npm
        npmModuleScope: "@inrupt/"
        bundleName: "VocabInruptClientApplication"

        typescriptVersion: "^4.1.3"
        rollupVersion: "^2.36.1"
        rollupTypescriptPluginVersion: "^0.29.0"
        rollupCommonjsPluginVersion: "^17.0.0"
        rollupNodeResolveVersion: "^11.0.1"

        publish:
        - key: "npmLocal"
          command: "npm unpublish --force --registry http://localhost:4873/ && npm install --registry http://localhost:4873/ && npm run build && npm publish --registry http://localhost:4873/"
        # The following command should only run in CI.
        - key: "npmPublic"
          command: "npm install --registry https://registry.npmjs.org/ && npm run build && npm publish --registry https://registry.npmjs.org/ --access public"
        packagingTemplates:
          - templateInternal: solidCommonVocabDependent/typescript/rdfjsRdfDataFactory/package.hbs
            fileName: package.json
          - templateInternal: generic/typescript/index.hbs
            fileName: index.ts
          - templateInternal: generic/typescript/tsconfig.hbs
            fileName: tsconfig.json
          - templateInternal: generic/typescript/rollup.config.hbs
            fileName: rollup.config.js  


  - programmingLanguage: TypeScript
    artifactVersion: "1.0.0"

    artifactDirectoryName: TypeScript-VocabTerm-rdfjs-RdfDataFactory
    sourceFileExtension: ts
    artifactSuffix: -vocabterm-rdfjs-rdfdatafactory

    solidCommonVocabVersion: "^1.0.0"
    rdfjsImplVersion: "^1.0.4"
    templateInternal: solidCommonVocabDependent/typescript/rdfjsRdfDataFactory/vocab.hbs

    packaging:
      - packagingTool: npm
        npmModuleScope: "@inrupt/"
        bundleName: "VocabInruptClientApplication"

        typescriptVersion: "^4.1.3"
        rollupVersion: "^2.36.1"
        rollupTypescriptPluginVersion: "^0.29.0"
        rollupCommonjsPluginVersion: "^17.0.0"
        rollupNodeResolveVersion: "^11.0.1"

        publish:
          - key: "npmLocal"
            command: "npm unpublish --force --registry http://localhost:4873/ && npm install --registry http://localhost:4873/ && npm run build && npm publish --registry http://localhost:4873/"
          # The following command should only run in CI.
          - key: "npmPublic"
            command: "npm install --registry https://registry.npmjs.org/ && npm run build && npm publish --registry https://registry.npmjs.org/ --access public"
        packagingTemplates:
          - templateInternal: solidCommonVocabDependent/typescript/rdfjsRdfDataFactory/package.hbs
            fileName: package.json
          - templateInternal: generic/typescript/index.hbs
            fileName: index.ts
          - templateInternal: generic/typescript/tsconfig.hbs
            fileName: tsconfig.json
          - templateInternal: generic/typescript/rollup.config.hbs
            fileName: rollup.config.js


vocabList:
  - description: Sample vocabulary - just for illustration.
    inputResources:
      - CopyOfVocab/inrupt-sample-client-app.ttl
