name: 'Generator version retrieval'
description: 'Retrieves the generator version from a YAML file.'
inputs:
  vocab-config-path:
    description: 'The path to the YAML config'
    required: true
outputs:
  vocab-generator-version:
    description: 'The required version'
runs:
  using: 'node16'
  main: 'dist/index.js'
