on:
  push:
    branches:
      - master

jobs:
    publish_on_push:
        runs-on: ubuntu-20.04
        strategy:
          matrix:
            vocab: [
                "common-rdf/Vocab-List-Common-Rdf.yml",
                "solid-rdf/Vocab-List-Solid.yml",
                "inrupt-rdf/Core/Vocab-List-Inrupt-Core.yml",
                "inrupt-rdf/Service/Vocab-List-Inrupt-Service.yml",
                "inrupt-rdf/Test/Vocab-List-Test.yml"
            ]
        name: CD for ${{ matrix.vocab }}
        steps:
        # Setup.
        - name: Checkout repo
          uses: actions/checkout@v2
        # Initializes node for the runner.
        - name: Node setup
          uses: actions/setup-node@v1
          with:
            node-version: '12.12.0'
            registry-url: https://npm.pkg.github.com/
            scope: '@inrupt'
        # The following step sets up Maven.
        - name: Set up JDK 11
          uses: actions/setup-java@v1.4.3
          with:
            java-version: 11
            # These values are used in the `settings.xml` Maven config file.
            server-id: cloudsmith-development # Value of the distributionManagement/repository/id field of the pom.xml
            server-username: ${{ secrets.CLOUDSMITH_USERNAME }}
            server-password: ${{ secrets.CLOUDSMITH_PASSWORD }}
        - name: Generate proper Maven settings
          uses: ./.github/fill-template
          with:
            template-path: ./.github/maven-settings.hbs
            output-path: ./settings.xml
          env:
            SERVER_ID_RELEASE: cloudsmith-staging
            SERVER_URL_RELEASE: https://maven.cloudsmith.io/inrupt/sdk-staging/
            SERVER_ID_SNAPSHOT: cloudsmith-development
            SERVER_URL_SNAPSHOT: https://maven.cloudsmith.io/inrupt/sdk-development/
            SERVER_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
            SERVER_PASSWORD: ${{ secrets.CLOUDSMITH_PASSWORD }}
        # The following action is defined in the current repo.
        # It reads the expected generator version from the YAML file.
        - name: Get generator version
          uses: ./.github/artifact-generator-version/
          id: generator-version-common
          with:
            vocab-config-path: ${{ matrix.vocab }}

        # Installs the Artifact Generator from its GitHub package.
        # The package is renamed in order to enable having different versions
        # side-by-side.
        - name: Install Artifact Generator
          run: npm install artifact-generator${{steps.generator-version-common.outputs.vocab-generator-version}}@npm:@inrupt/lit-artifact-generator@${{steps.generator-version-common.outputs.vocab-generator-version}} --registry https://npm.pkg.github.com/inrupt
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        # Note: This only pushes to Cloudsmith (not npm), because it does not
        # increment the version number, which is fine for Maven SNAPSHOT
        # versions.
        - run: node node_modules/artifact-generator${{steps.generator-version-common.outputs.vocab-generator-version}}/index.js generate -l ${{ matrix.vocab }} --noprompt -p cloudsmith
          env:
              NODE_AUTH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        - name: Upload log for debug
          # Only upload if the previous step failed.
          if: failure()
          uses: actions/upload-artifact@v1.0.0
          with:
            path: mvn-deploy.log
            name: mvn-deploy
