on: [pull_request]

jobs:
    validate_pr:
        runs-on: ubuntu-20.04
        strategy:
          matrix:
            vocab: [
              "common-rdf/Common/Vocab-List-Common-Rdf.yml",
              "lit-rdf/Common/Vocab-List-Lit-Common.yml",
              "inrupt-rdf/Common/Vocab-List-Inrupt-Common.yml",
              "inrupt-rdf/Service/Vocab-List-Inrupt-Service.yml",
              "solid-rdf/Common/Vocab-List-Solid-Common.yml"
            ]
        name: CI for ${{ matrix.vocab }}
        steps:
        # Setup.
        - name: Checkout repo
          uses: actions/checkout@v2
        # Initializes node for the runner.
        - name: Node setup
          uses: actions/setup-node@v1
          with:
            node-version: '12.12.0'
            registry-url: https://npm.pkg.github.com/
            scope: '@inrupt'
        # The following step sets up Maven.
        - name: Set up JDK 11
          uses: actions/setup-java@v1.4.3
          with:
            java-version: 11
            # These values are used in the `settings.xml` Maven config file.
            server-id: cloudsmith-development # Value of the distributionManagement/repository/id field of the pom.xml
            server-username: ${{ secrets.CLOUDSMITH_USERNAME }}
            server-password: ${{ secrets.CLOUDSMITH_PASSWORD }}
        - name: Generate proper Maven settings
          uses: ./.github/fill-template
          with:
            template-path: ./.github/maven-settings.hbs
            output-path: ./settings.xml
          env:
            SERVER_ID_RELEASE: cloudsmith-staging
            SERVER_URL_RELEASE: https://maven.cloudsmith.io/inrupt/sdk-staging/
            SERVER_ID_SNAPSHOT: cloudsmith-development
            SERVER_URL_SNAPSHOT: https://maven.cloudsmith.io/inrupt/sdk-development/
            SERVER_USERNAME: ${{ secrets.CLOUDSMITH_USERNAME }}
            SERVER_PASSWORD: ${{ secrets.CLOUDSMITH_PASSWORD }}
        # The following action is defined in the current repository.
        # It reads the expected generator version from the YAML file.
        - name: Get generator version
          uses: ./.github/artifact-generator-version/
          id: generator-version-common
          with:
            vocab-config-path: ${{ matrix.vocab }}

        # Installs the Artifact Generator from its GitHub package.
        # The package is renamed in order to enable having different versions
        # side-by-side.
        - name: Install Artifact Generator
          run: npm install artifact-generator${{steps.generator-version-common.outputs.vocab-generator-version}}@npm:@inrupt/lit-artifact-generator@${{steps.generator-version-common.outputs.vocab-generator-version}} --registry https://npm.pkg.github.com/inrupt
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        - run: node node_modules/artifact-generator${{steps.generator-version-common.outputs.vocab-generator-version}}/index.js generate -l ${{ matrix.vocab }} --noprompt
        env:
            NODE_AUTH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
