name: Release

on: 
    push:
        tags: 
            - v[0-9]+.[0-9]+.[0-9]+

jobs:
  npm_publish:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        vocab: [
            "common-rdf/Vocab-List-Common-Rdf.yml",
            "solid-rdf/Vocab-List-Solid.yml",
            "inrupt-rdf/Core/Vocab-List-Inrupt-Core.yml",
            "inrupt-rdf/Service/Vocab-List-Inrupt-Service.yml",
            "inrupt-rdf/Test/Vocab-List-Inrupt-Test.yml"
        ]
    name: npm release for ${{ matrix.vocab }}
    steps:
     # Makes the current repository available to the workflow.
    - name: Checkout repo
      uses: actions/checkout@v2
    # Initializes Node and npm to install the Artifact Generator from GitHub
    # packages.
    - name: Node setup
      uses: actions/setup-node@v1
      with:
        node-version: '12.12.0'
        registry-url: https://npm.pkg.github.com/
        scope: '@inrupt'
    # The following action is defined in the current repository.
    # It reads the expected Artifact Generator version from the YAML file.
    - name: Get generator version (Common)
      uses: ./.github/artifact-generator-version/
      id: generator-version-common
      with: 
        vocab-config-path: ${{ matrix.vocab }}
    # Installs the artifact generator from its GitHub package.
    # The package is renamed in order to enable having different versions
    # side-by-side.
    - name: Generator installation
      run: npm install artifact-generator${{steps.generator-version-common.outputs.vocab-generator-version}}@npm:@inrupt/artifact-generator@${{steps.generator-version-common.outputs.vocab-generator-version}} --registry https://npm.pkg.github.com/inrupt
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    - name: npm cleanup
      run: rm /home/runner/work/_temp/.npmrc
    # Re-initializes npm to publish to NPMJS.
    - name: Node setup
      uses: actions/setup-node@v1
      with:
        node-version: '12.12.0'
        registry-url: https://registry.npmjs.com/
        scope: '@inrupt'
    # Use the generator to generate and publish the npm package.
    # Maven packages are published by the CD script, and do not need to be
    # published again on release.
    - name: Generation and publication
      run: node node_modules/artifact-generator${{steps.generator-version-common.outputs.vocab-generator-version}}/index.js generate -l ${{ matrix.vocab }} -p npmPublic --noprompt
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
